# Generated by Django 4.0.5 on 2022-06-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_alter_communitypost_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='community_id',
            new_name='community',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user_id',
            new_name='user',
        ),
    ]
