# Generated by Django 4.0.5 on 2022-06-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0013_rename_community_id_membership_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='communities.community'),
        ),
    ]
