# Generated by Django 4.0.5 on 2022-06-07 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0014_alter_membership_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
