# Generated by Django 4.0.5 on 2022-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0020_alter_favrecipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='favrecipe',
            name='img',
            field=models.CharField(default='img', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
